from typing import Final

# Each category maps to CLIP text prompts; best per-category similarity is used.
OBJECT_CATEGORIES: Final[dict[str, list[str]]] = {
    "person":       ["a photo of a person", "a photo of a man or woman walking", "a photo of people"],
    "car":          ["a photo of a car", "a photo of an automobile or sedan", "a photo of a parked car"],
    "truck":        ["a photo of a truck", "a photo of a lorry or delivery van", "a photo of a pickup truck"],
    "bus":          ["a photo of a bus", "a photo of a coach or double-decker bus", "a photo of a transit bus"],
    "motorcycle":   ["a photo of a motorcycle", "a photo of a motorbike or scooter", "a photo of a moped"],
    "bicycle":      ["a photo of a bicycle", "a photo of a bike leaning against something", "a photo of a cyclist"],
    "boat":         ["a photo of a boat", "a photo of a sailboat or yacht", "a photo of a river boat or barge"],
    "ship":         ["a photo of a large ship", "a photo of a cargo vessel or cruise ship", "a photo of a ferry"],
    "aircraft":     ["a photo of an airplane", "a photo of a helicopter", "a photo of an aircraft in the sky"],
    "train":        ["a photo of a train", "a photo of a tram or subway car", "a photo of a railway carriage"],
    "animal":       ["a photo of an animal", "a photo of a dog or cat", "a photo of wildlife in nature"],
    "building":     ["a photo of a building", "a photo of a house or apartment block", "a photo of an office or commercial building"],
    "bridge":       ["a photo of a bridge", "a photo of an overpass or viaduct", "a photo of a pedestrian bridge"],
    "tower":        ["a photo of a tower", "a photo of a clock tower or bell tower", "a photo of a communication tower"],
    "skyscraper":   ["a photo of a skyscraper", "a photo of a tall modern building", "a photo of a high-rise building"],
    "monument":     ["a photo of a monument", "a photo of a statue or sculpture outdoors", "a photo of a war memorial"],
    "landmark":     ["a photo of a famous landmark", "a photo of a historic structure", "a photo of a tourist attraction"],
    "tree":         ["a photo of a tree", "a photo of a large isolated tree", "a photo of a palm tree or oak", "a photo of trees in a row", "a photo of a cluster of trees", "a photo of a forest of trees"],
    "forest":       ["a photo of a forest", "a photo of dense trees or woodland", "a photo of a wooded area", "a photo of a grove of trees"],
    "plant":        ["a photo of a plant or shrub", "a photo of a bush or potted plant", "a photo of a decorative plant or hedge"],
    "rock":         ["a photo of a rock or boulder", "a photo of a decorative stone", "a photo of a large standalone rock"],
    "bench":        ["a photo of a park bench", "a photo of outdoor seating", "a photo of a wooden bench"],
    "chair":        ["a photo of a chair", "a photo of outdoor furniture", "a photo of a patio chair or stool"],
    "table":        ["a photo of a table", "a photo of a picnic table", "a photo of an outdoor dining table"],
    "sign":         ["a photo of a sign", "a photo of a road sign or signpost", "a photo of a billboard or advertisement"],
    "streetlight":  ["a photo of a streetlight", "a photo of a lamppost", "a photo of a light pole at night"],
    "trash_bin":    ["a photo of a trash bin", "a photo of a garbage can or dumpster", "a photo of a recycling bin"],
    "barrier":      ["a photo of a barrier", "a photo of a fence or railing", "a photo of bollards or road barriers"],
    "umbrella":     ["a photo of an umbrella", "a photo of a beach umbrella or parasol", "a photo of a patio sunshade"],
    "cart":         ["a photo of a cart or trolley", "a photo of a shopping cart", "a photo of a market stall cart"],
    "kiosk":        ["a photo of a kiosk or booth", "a photo of a ticket booth", "a photo of a street vendor stand"],
    "luggage":      ["a photo of luggage or a suitcase", "a photo of bags or backpacks", "a photo of a travel bag"],
    "other":        ["a photo of an unidentified object", "a miscellaneous item outdoors"],
}

ENVIRONMENT_CATEGORIES: Final[dict[str, list[str]]] = {
    "sky":          ["a photo of the sky", "a clear blue sky", "an overcast or cloudy sky"],
    "clouds":       ["a photo of clouds in the sky", "a photo of storm clouds", "a photo of white fluffy clouds"],
    "water":        ["a photo of water", "a photo of a body of water", "a calm water surface"],
    "river":        ["a photo of a river", "a photo of a flowing river or stream", "a photo of a riverbank"],
    "ocean":        ["a photo of the ocean", "a photo of the sea", "ocean waves on a shore"],
    "lake":         ["a photo of a lake", "a photo of a still lake or pond", "a photo of a lakeside"],
    "ground":       ["a photo of the ground", "a photo of bare earth or soil", "a flat open ground surface"],
    "dirt":         ["a photo of dirt or soil", "a photo of bare muddy ground", "a photo of a dirt path or field"],
    "grass":        ["a photo of grass", "a photo of a grassy lawn or meadow", "a photo of green grass on the ground"],
    "sand":         ["a photo of sand", "a photo of a sandy beach or desert", "a photo of sand dunes"],
    "snow":         ["a photo of snow", "a photo of a snow-covered ground", "a snowy landscape or snowfield"],
    "ice":          ["a photo of ice", "a photo of a frozen lake or river", "a photo of ice on the ground"],
    "mountain":     ["a photo of a mountain", "a photo of a mountain range or peak", "a photo of a hillside or slope"],
    "road":         ["a photo of a road or street", "a photo of asphalt pavement", "a photo of a highway or path"],
    "wall":         ["a photo of a wall", "a photo of a building facade or exterior wall", "a photo of a concrete or brick wall"],
    "mud":          ["a photo of mud", "a photo of muddy ground or a muddy puddle", "a photo of wet muddy soil"],
    "other_environment": ["a photo of a natural landscape", "a photo of an outdoor environment", "an environmental background"],
}
